/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package assignments_package;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Norhan
 */
public class B_6_2018170833_NorhanMahmoudMohamed extends javax.swing.JFrame {

 ///
   public abstract class CD {
    private  final String name;
    private int quantity;

    public CD(String name) {
        this.name = name;
    }

 
    public CD(String name, int quantity) {
        this.name = name;
        this.quantity = quantity;
    }

    public String getName() {
        return name;
    }

   

    public int getQuantity() {
        return quantity;
    }

    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }
    public   void IncreaseTheCDQuantityBy(int AddtionalQuantity)
    {
        quantity =quantity+AddtionalQuantity;
    }
    public abstract  void DisplayInf();
}
  ///
    ///
    public class Movie extends CD{
   private float quration;

    public Movie(float quration, String name, int quantity) {
        super(name, quantity);
        this.quration = quration;
    }

    public float getQuration() {
        return quration;
    }

    public void setQuration(float quration) {
        this.quration = quration;
    }

    @Override
    public void DisplayInf() {
                  JOptionPane.showMessageDialog(null,"Name Movie :"+getName(), "Movie",JOptionPane.INFORMATION_MESSAGE);
          JOptionPane.showMessageDialog(null," Quantity Movie : "+getQuantity(), "Movie",JOptionPane.INFORMATION_MESSAGE);
          JOptionPane.showMessageDialog(null,"Quration movie : "+getQuration(), "Movie",JOptionPane.INFORMATION_MESSAGE);
          JOptionPane.showMessageDialog(null,"    ❤❤❤  Thanks  ❤❤❤", "Movie",JOptionPane.INFORMATION_MESSAGE);

    }

   
}
////
   ///// 
    
    
   public class Series extends CD{
    private  int numberOfEpisodes;

    public Series(int numberOfEpisodes, String name, int quantity) {
        super(name, quantity);
        this.numberOfEpisodes = numberOfEpisodes;
    }


    public int getNumberOfEpisodes() {
        return numberOfEpisodes;
    }

    public void setNumberOfEpisodes(int numberOfEpisodes) {
        this.numberOfEpisodes = numberOfEpisodes;
    }

    @Override
    public void DisplayInf() {
                  JOptionPane.showMessageDialog(null,"Name Serise : "+getName(), "Serise",JOptionPane.INFORMATION_MESSAGE);
          JOptionPane.showMessageDialog(null,"Quantity Serise : "+getQuantity(), "Serise",JOptionPane.INFORMATION_MESSAGE);
          JOptionPane.showMessageDialog(null,"Number Of Episodes Serise : "+getNumberOfEpisodes(), "Serise",JOptionPane.INFORMATION_MESSAGE);
          JOptionPane.showMessageDialog(null,"    ❤❤❤  Thanks  ❤❤❤", "Serise",JOptionPane.INFORMATION_MESSAGE);

    }
    
}

  ////  
    ArrayList<CD> cds;
    Movie movie;
    Series series;
    public B_6_2018170833_NorhanMahmoudMohamed() {
        initComponents();
        cds=new ArrayList<>();
        radioButtonMovies.setSelected(true);
        txtNumberOfEpisodes.setEditable(false);
        //color = Color.DIMGRAY;
        txtNumberOfEpisodes.setBackground(java.awt.Color.GRAY);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupChoise = new javax.swing.ButtonGroup();
        jLabel5 = new javax.swing.JLabel();
        txtMovieDuration = new javax.swing.JTextField();
        txtNumberOfEpisodes = new javax.swing.JTextField();
        btnAddCD = new javax.swing.JButton();
        btnRetreiveCDInf = new javax.swing.JButton();
        btnRentTheCD = new javax.swing.JButton();
        btnIncreaseCDQuantity = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        ladName = new javax.swing.JLabel();
        labQuantity = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtQuantity = new javax.swing.JTextField();
        radioButtonMovies = new javax.swing.JRadioButton();
        radioButtonSeries = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel5.setText("Number Of Episodes");

        txtMovieDuration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMovieDurationActionPerformed(evt);
            }
        });

        txtNumberOfEpisodes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumberOfEpisodesActionPerformed(evt);
            }
        });

        btnAddCD.setText("Add New CD");
        btnAddCD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCDActionPerformed(evt);
            }
        });

        btnRetreiveCDInf.setText("Retreive CD Inf");
        btnRetreiveCDInf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetreiveCDInfActionPerformed(evt);
            }
        });

        btnRentTheCD.setText("Rent The CD");
        btnRentTheCD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRentTheCDActionPerformed(evt);
            }
        });

        btnIncreaseCDQuantity.setText("Increase CD Quantity");
        btnIncreaseCDQuantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIncreaseCDQuantityActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("  CD Infarmation");

        ladName.setText("CD Name");

        labQuantity.setText("CD Quantity");

        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });

        txtQuantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQuantityActionPerformed(evt);
            }
        });

        buttonGroupChoise.add(radioButtonMovies);
        radioButtonMovies.setText("Movie");
        radioButtonMovies.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButtonMoviesActionPerformed(evt);
            }
        });

        buttonGroupChoise.add(radioButtonSeries);
        radioButtonSeries.setText("Series");
        radioButtonSeries.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButtonSeriesActionPerformed(evt);
            }
        });

        jLabel4.setText("Movie Duration ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labQuantity)
                            .addComponent(ladName))
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtName, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                            .addComponent(txtQuantity))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAddCD)
                    .addComponent(btnRentTheCD)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(radioButtonMovies)
                            .addComponent(jLabel4)
                            .addComponent(txtMovieDuration, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRetreiveCDInf)
                    .addComponent(btnIncreaseCDQuantity)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(radioButtonSeries)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtNumberOfEpisodes))))
                .addGap(20, 20, 20))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnAddCD, btnIncreaseCDQuantity, btnRentTheCD, btnRetreiveCDInf});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtMovieDuration, txtNumberOfEpisodes});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ladName)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labQuantity))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(radioButtonMovies)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtMovieDuration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(radioButtonSeries)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNumberOfEpisodes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddCD)
                    .addComponent(btnRetreiveCDInf))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRentTheCD)
                    .addComponent(btnIncreaseCDQuantity))
                .addGap(0, 23, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnAddCD, btnIncreaseCDQuantity, btnRentTheCD, btnRetreiveCDInf});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtMovieDuration, txtNumberOfEpisodes});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtMovieDurationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMovieDurationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMovieDurationActionPerformed

    private void txtNumberOfEpisodesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumberOfEpisodesActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtNumberOfEpisodesActionPerformed

    private void btnAddCDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCDActionPerformed
        // TODO add your handling code here:
        float v=(float) 4.9;
        if ( radioButtonMovies.isSelected())
        {
            if(!txtName.getText().equals("")&&(!txtQuantity.getText().equals(""))&&
                (!txtMovieDuration.getText().equals("")))
            {
                if(isFloatNumberOrNot(txtMovieDuration.getText())&&
                    ((isFloatNumberOrNot(txtQuantity.getText()))))
                { movie = new Movie(Float.valueOf(txtMovieDuration.getText()), txtName.getText(),
                    Integer.valueOf(txtQuantity.getText()));
                cds.add(movie);
                JOptionPane.showMessageDialog(null,"    ❤❤❤ the movie is added successfully ❤❤❤", "",JOptionPane.INFORMATION_MESSAGE);
            }
            else
            {
                JOptionPane.showMessageDialog(null,"Quantity and Duration must be Number :)", "",JOptionPane.ERROR_MESSAGE);

            }
        }
        else
        {
            JOptionPane.showMessageDialog(null,"Must Enter All Information Movie :)", "",JOptionPane.ERROR_MESSAGE);

        }
        }
        else if(radioButtonSeries.isSelected())
        {
            if(!txtName.getText().equals("")&&(!txtQuantity.getText().equals(""))&&
                (!txtNumberOfEpisodes.getText().equals("")))
            {
                if(isIntNumberOrNot(txtNumberOfEpisodes.getText())&&isIntNumberOrNot(txtQuantity.getText()))
                {
                    series= new Series(Integer.valueOf(txtNumberOfEpisodes.getText()), txtName.getText(),
                        Integer.valueOf(txtQuantity.getText()));
                    cds.add(series);
                    JOptionPane.showMessageDialog(null,"    ❤❤❤ the series is added successfully ❤❤❤", "",JOptionPane.INFORMATION_MESSAGE);
                }
                else
                {
                    JOptionPane.showMessageDialog(null,"Number Of Episodes and Quantity must be Number :)", "",JOptionPane.ERROR_MESSAGE);
                }
            }
            else
            {
                JOptionPane.showMessageDialog(null,"Must Enter All Information Series :)", "",JOptionPane.ERROR_MESSAGE);
            }
        }
        else
        {
            JOptionPane.showMessageDialog(null,"Not added successfully ,Try Again ","",JOptionPane.WARNING_MESSAGE);

        }
        txtName.setText("");
        txtNumberOfEpisodes.setText("");
        txtQuantity.setText("");
        txtMovieDuration.setText("");
    }//GEN-LAST:event_btnAddCDActionPerformed

    private void btnRetreiveCDInfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetreiveCDInfActionPerformed
        // TODO add your handling code here:
        boolean b =true;
        for (int i = 0; i < cds.size(); i++) {
            //  CD cd= cds.get(i);
            if(txtName.getText().equals(cds.get(i).getName()))
            {
                cds.get(i).DisplayInf();
                b=true;
                break;
            }
            else
            {
                b=false;
            }

        }
        if (b==false)
        {
            JOptionPane.showMessageDialog(null,"This CD Not Found :)", "",JOptionPane.ERROR_MESSAGE);
        }
        txtName.setText("");
        txtNumberOfEpisodes.setText("");
        txtQuantity.setText("");
        txtMovieDuration.setText("");
    }//GEN-LAST:event_btnRetreiveCDInfActionPerformed

    private void btnRentTheCDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRentTheCDActionPerformed
        // TODO add your handling code here:
        boolean b=true;
        for (int i = 0; i < cds.size(); i++) {
            //  CD cd= cds.get(i);
            if(txtName.getText().equals(cds.get(i).getName()))
            {
                if(cds.get(i).getQuantity() >0)
                {
                    cds.get(i).setQuantity(cds.get(i).getQuantity()-1);
                    JOptionPane.showMessageDialog(null,"❤❤❤ Rent ❤❤❤", "❤❤❤❤❤❤❤❤❤",JOptionPane.INFORMATION_MESSAGE);

                }
                else if (cds.get(i).getQuantity() <=0)
                {
                    JOptionPane.showMessageDialog(null," This CD istnot Exist in Stok :)", "",JOptionPane.INFORMATION_MESSAGE);
                }
                b=true;
                break;
            }
            else
            {
                b=false;
            }

        }
        if (b==false)
        {
            JOptionPane.showMessageDialog(null,"This CD Not Found :)", "",JOptionPane.ERROR_MESSAGE);
        }
        txtName.setText("");
        txtNumberOfEpisodes.setText("");
        txtQuantity.setText("");
        txtMovieDuration.setText("");
    }//GEN-LAST:event_btnRentTheCDActionPerformed

    private void btnIncreaseCDQuantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIncreaseCDQuantityActionPerformed
        // TODO add your handling code here:
        boolean b=true;
        for (int i = 0; i < cds.size(); i++) {
            //  CD cd= cds.get(i);
            if(txtName.getText().equals(cds.get(i).getName()))
            {
                if(isIntNumberOrNot(txtQuantity.getText()))
                {
                    cds.get(i).IncreaseTheCDQuantityBy(Integer.valueOf(txtQuantity.getText()));
                    JOptionPane.showMessageDialog(null,"Tis Quantity Increase :)", "",JOptionPane.INFORMATION_MESSAGE);
                }
                else
                {
                    JOptionPane.showMessageDialog(null,"You Must Enter Quantity As Number :)", "",JOptionPane.ERROR_MESSAGE);

                }
                b=true;
                break;
            }

            else
            {
                b=false;
            }

        }
        if (b==false)
        {
            JOptionPane.showMessageDialog(null,"This CD Not Exist :)", "",JOptionPane.ERROR_MESSAGE);
        }

        txtName.setText("");
        txtNumberOfEpisodes.setText("");
        txtQuantity.setText("");
        txtMovieDuration.setText("");
    }//GEN-LAST:event_btnIncreaseCDQuantityActionPerformed
   public static boolean isIntNumberOrNot(String input)
	{
		try
		{
			Integer.parseInt(input);
		}
		catch(NumberFormatException ex)
		{
			return false;
		}
		return true;
	}
   
   public static boolean isFloatNumberOrNot(String input)
   {
               try
		{
	         float f=   Float.parseFloat(input);
		}
		catch(NumberFormatException ex)
		{
			return false;
		}
		return true;
   }
    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtNameActionPerformed

    private void txtQuantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQuantityActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtQuantityActionPerformed

    private void radioButtonMoviesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioButtonMoviesActionPerformed
        // TODO add your handling code here:
        radioButtonMovies.setSelected(true);
        txtNumberOfEpisodes.setEditable(false);
        //color = Color.DIMGRAY;
        txtNumberOfEpisodes.setBackground(java.awt.Color.GRAY);
        txtMovieDuration.setBackground(java.awt.Color.WHITE);
        txtMovieDuration.setEditable(true);
    }//GEN-LAST:event_radioButtonMoviesActionPerformed

    private void radioButtonSeriesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioButtonSeriesActionPerformed
        // TODO add your handling code here:
        radioButtonSeries.setSelected(true);
        txtMovieDuration.setEditable(false);
        //color = Color.DIMGRAY;
        txtMovieDuration.setBackground(java.awt.Color.GRAY);
        txtNumberOfEpisodes.setEditable(true);
        txtNumberOfEpisodes.setBackground(java.awt.Color.WHITE);
    }//GEN-LAST:event_radioButtonSeriesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(B_6_2018170833_NorhanMahmoudMohamed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(B_6_2018170833_NorhanMahmoudMohamed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(B_6_2018170833_NorhanMahmoudMohamed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(B_6_2018170833_NorhanMahmoudMohamed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new B_6_2018170833_NorhanMahmoudMohamed().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddCD;
    private javax.swing.JButton btnIncreaseCDQuantity;
    private javax.swing.JButton btnRentTheCD;
    private javax.swing.JButton btnRetreiveCDInf;
    private javax.swing.ButtonGroup buttonGroupChoise;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel labQuantity;
    private javax.swing.JLabel ladName;
    private javax.swing.JRadioButton radioButtonMovies;
    private javax.swing.JRadioButton radioButtonSeries;
    private javax.swing.JTextField txtMovieDuration;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtNumberOfEpisodes;
    private javax.swing.JTextField txtQuantity;
    // End of variables declaration//GEN-END:variables
}
